name: alerta_vital_frontend
description: AlertaVital
publish_to: "none"
version: 0.2.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  google_fonts: ^6.2.1
  flutter_multi_formatter: ^2.12.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/AlertaVital.png
