// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqW1SpYvsY5D8Hr3HfGz9OFr1B0_ekWwU',
    appId: '1:162915256207:web:676203a5315fc4b89eedfa',
    messagingSenderId: '162915256207',
    projectId: 'alertavital-5457e',
    authDomain: 'alertavital-5457e.firebaseapp.com',
    storageBucket: 'alertavital-5457e.firebasestorage.app',
    measurementId: 'G-0BWWMVVL6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMUry0MNL-TKC3GBPCMpY5OuoKh4duqm8',
    appId: '1:162915256207:android:d7610a3e72c97a8d9eedfa',
    messagingSenderId: '162915256207',
    projectId: 'alertavital-5457e',
    storageBucket: 'alertavital-5457e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2lDy_PMh9TasJps1IbtjLfU57tQJmDhQ',
    appId: '1:162915256207:ios:ea3bd04cb023a71f9eedfa',
    messagingSenderId: '162915256207',
    projectId: 'alertavital-5457e',
    storageBucket: 'alertavital-5457e.firebasestorage.app',
    iosBundleId: 'com.example.seniorLocatorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2lDy_PMh9TasJps1IbtjLfU57tQJmDhQ',
    appId: '1:162915256207:ios:ea3bd04cb023a71f9eedfa',
    messagingSenderId: '162915256207',
    projectId: 'alertavital-5457e',
    storageBucket: 'alertavital-5457e.firebasestorage.app',
    iosBundleId: 'com.example.seniorLocatorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqW1SpYvsY5D8Hr3HfGz9OFr1B0_ekWwU',
    appId: '1:162915256207:web:428c686495371e559eedfa',
    messagingSenderId: '162915256207',
    projectId: 'alertavital-5457e',
    authDomain: 'alertavital-5457e.firebaseapp.com',
    storageBucket: 'alertavital-5457e.firebasestorage.app',
    measurementId: 'G-7KSXYTVMNT',
  );
}
